# ============================================================
# AETHER LINK - USER MODEL (UPGRADED - COMPLETE)
# ============================================================

from sqlalchemy import Column, Integer, String, Boolean, Text, DateTime, Enum as SQLEnum, BigInteger
from sqlalchemy.sql import func
from sqlalchemy.orm import relationship
import enum
from ..core.database import Base


class UserRole(str, enum.Enum):
    """User role enumeration."""
    STUDENT = "student"
    TEACHER = "teacher"
    ADMIN = "admin"
    CLIENT = "client"        # NEW: Software House client
    DEVELOPER = "developer"  # NEW: Software House developer


class User(Base):
    __tablename__ = "users"

    # ============================================================
    # PRIMARY KEY
    # ============================================================
    id = Column(Integer, primary_key=True, index=True)
    
    # ============================================================
    # AUTHENTICATION
    # ============================================================
    email = Column(String(255), unique=True, index=True, nullable=False)
    username = Column(String(100), unique=True, index=True, nullable=False)
    hashed_password = Column(String(255), nullable=False)
    
    # ============================================================
    # PROFILE
    # ============================================================
    full_name = Column(String(255), nullable=False)
    phone = Column(String(20), nullable=True)
    profile_picture = Column(String(500), nullable=True)
    bio = Column(Text, nullable=True)
    
    # ============================================================
    # ROLE & STATUS
    # ============================================================
    role = Column(
        SQLEnum(UserRole, values_callable=lambda x: [e.value for e in x]),
        default=UserRole.STUDENT,
        nullable=False
    )
    is_verified = Column(Boolean, default=False, nullable=False)
    is_active = Column(Boolean, default=True, nullable=False)
    
    # ============================================================
    # NEW: STUDENT ID (8-digit unique identifier)
    # ============================================================
    student_id = Column(String(20), unique=True, nullable=True, index=True)
    # Format: AETH-XXXXX (e.g., AETH-00042)
    # Auto-generated by trigger in database
    
    # ============================================================
    # NEW: SECURITY & LOGIN TRACKING
    # ============================================================
    failed_login_attempts = Column(Integer, default=0, nullable=False)
    locked_until = Column(DateTime(timezone=True), nullable=True)
    # Account locks for 30 minutes after 5 failed attempts
    
    # ============================================================
    # TIMESTAMPS
    # ============================================================
    last_login = Column(DateTime(timezone=True), nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at = Column(DateTime(timezone=True), onupdate=func.now(), nullable=True)
    deleted_at = Column(DateTime(timezone=True), nullable=True)
    
    # ============================================================
    # RELATIONSHIPS (EXISTING - KEPT)
    # ============================================================
    
    # Teacher: Courses they teach
    taught_courses = relationship(
        "Course",
        back_populates="teacher",
        foreign_keys="Course.teacher_id",
        cascade="all, delete-orphan"
    )
    
    # Student: Enrollments
    enrollments = relationship(
        "Enrollment",
        back_populates="student",
        foreign_keys="Enrollment.student_id",
        cascade="all, delete-orphan"
    )
    
    # Admin: Payments they verified
    verified_payments = relationship(
        "Payment",
        back_populates="verified_by_user",
        foreign_keys="Payment.verified_by",
        cascade="all, delete-orphan"
    )
    
    # Student: Payments they made
    payments = relationship(
        "Payment",
        back_populates="student",
        foreign_keys="Payment.student_id",
        cascade="all, delete-orphan"
    )
    
    # Admin: Enrollments they verified
    verified_enrollments = relationship(
        "Enrollment",
        back_populates="verified_by_user",
        foreign_keys="Enrollment.payment_verified_by",
        cascade="all, delete-orphan"
    )
    
    # ============================================================
    # NEW: FORUM RELATIONSHIPS
    # ============================================================
    forum_topics = relationship(
        "ForumTopic",
        back_populates="created_by_user",
        foreign_keys="ForumTopic.created_by",
        cascade="all, delete-orphan"
    )
    
    forum_replies = relationship(
        "ForumReply",
        back_populates="created_by_user",
        foreign_keys="ForumReply.created_by",
        cascade="all, delete-orphan"
    )
    
    forum_reply_likes = relationship(
        "ForumReplyLike",
        back_populates="user",
        foreign_keys="ForumReplyLike.user_id",
        cascade="all, delete-orphan"
    )
    
    # ============================================================
    # NEW: ASSIGNMENT RELATIONSHIPS
    # ============================================================
    assignment_submissions = relationship(
        "AssignmentSubmission",
        back_populates="student",
        foreign_keys="AssignmentSubmission.student_id",
        cascade="all, delete-orphan"
    )
    
    graded_submissions = relationship(
        "AssignmentSubmission",
        back_populates="graded_by_user",
        foreign_keys="AssignmentSubmission.graded_by",
        cascade="all, delete-orphan"
    )
    
    # ============================================================
    # NEW: CHAT RELATIONSHIPS
    # ============================================================
    messages_sent = relationship(
        "Message",
        back_populates="sender",
        foreign_keys="Message.sender_id",
        cascade="all, delete-orphan"
    )
    
    course_chat_messages = relationship(
        "CourseChatMessage",
        back_populates="sender",
        foreign_keys="CourseChatMessage.sender_id",
        cascade="all, delete-orphan"
    )
    
    conversations_created = relationship(
        "Conversation",
        back_populates="created_by_user",
        foreign_keys="Conversation.created_by",
        cascade="all, delete-orphan"
    )
    
    # ============================================================
    # NEW: REVIEW RELATIONSHIPS
    # ============================================================
    reviews = relationship(
        "Review",
        back_populates="student",
        foreign_keys="Review.student_id",
        cascade="all, delete-orphan"
    )
    
    review_helpful_votes = relationship(
        "ReviewHelpfulVote",
        back_populates="user",
        foreign_keys="ReviewHelpfulVote.user_id",
        cascade="all, delete-orphan"
    )
    
    # ============================================================
    # NEW: ANNOUNCEMENT RELATIONSHIPS
    # ============================================================
    announcement_reads = relationship(
        "AnnouncementRead",
        back_populates="user",
        foreign_keys="AnnouncementRead.user_id",
        cascade="all, delete-orphan"
    )
    
    announcements_created = relationship(
        "Announcement",
        back_populates="created_by_user",
        foreign_keys="Announcement.created_by",
        cascade="all, delete-orphan"
    )
    
    # ============================================================
    # NEW: CERTIFICATE RELATIONSHIPS
    # ============================================================
    certificates = relationship(
        "Certificate",
        back_populates="student",
        foreign_keys="Certificate.student_id",
        cascade="all, delete-orphan"
    )
    
    revoked_certificates = relationship(
        "Certificate",
        back_populates="revoked_by_user",
        foreign_keys="Certificate.revoked_by",
        cascade="all, delete-orphan"
    )
    
    # ============================================================
    # NEW: VIDEO WATCH PROGRESS
    # ============================================================
    video_progress = relationship(
        "VideoWatchProgress",
        back_populates="student",
        foreign_keys="VideoWatchProgress.student_id",
        cascade="all, delete-orphan"
    )
    
    # ============================================================
    # NEW: TEACHER INVITATIONS
    # ============================================================
    teacher_invitations = relationship(
        "TeacherInvitation",
        back_populates="invited_by_user",
        foreign_keys="TeacherInvitation.invited_by",
        cascade="all, delete-orphan"
    )
    
    # ============================================================
    # NEW: PATH ENROLLMENTS (Learning Paths)
    # ============================================================
    path_enrollments = relationship(
        "PathEnrollment",
        back_populates="student",
        foreign_keys="PathEnrollment.student_id",
        cascade="all, delete-orphan"
    )
    
    # ============================================================
    # NEW: NOTIFICATIONS
    # ============================================================
    notifications = relationship(
        "Notification",
        back_populates="user",
        foreign_keys="Notification.user_id",
        cascade="all, delete-orphan"
    )
    
    # ============================================================
    # NEW: REFRESH TOKENS (Supabase integration)
    # ============================================================
    refresh_tokens = relationship(
        "RefreshToken",
        back_populates="user",
        foreign_keys="RefreshToken.user_id",
        cascade="all, delete-orphan"
    )
    
    # ============================================================
    # NEW: USER SESSIONS (Logout All Devices)
    # ============================================================
    user_sessions = relationship(
        "UserSession",
        back_populates="user",
        foreign_keys="UserSession.user_id",
        cascade="all, delete-orphan"
    )
    
    # ============================================================
    # NEW: AUDIT LOG
    # ============================================================
    audit_logs = relationship(
        "AuditLog",
        back_populates="user",
        foreign_keys="AuditLog.user_id",
        cascade="all, delete-orphan"
    )
    
    # ============================================================
    # NEW: PASSWORD RESET RELATIONSHIPS (MISSING - ADDED)
    # ============================================================
    password_reset_requests = relationship(
        "PasswordReset",
        back_populates="user",
        foreign_keys="PasswordReset.user_id",
        cascade="all, delete-orphan"
    )
    
    password_reset_audit_logs = relationship(
        "PasswordResetAuditLog",
        back_populates="user",
        foreign_keys="PasswordResetAuditLog.user_id",
        cascade="all, delete-orphan"
    )
    
    # ============================================================
    # NEW: SESSION REVOCATION LOG (MISSING - ADDED)
    # ============================================================
    session_revocation_logs = relationship(
        "SessionRevocationLog",
        foreign_keys="SessionRevocationLog.user_id",
        cascade="all, delete-orphan"
    )
    
    # ============================================================
    # NEW: TOKEN REVOCATION LOG (MISSING - ADDED)
    # ============================================================
    token_revocation_logs = relationship(
        "TokenRevocationLog",
        foreign_keys="TokenRevocationLog.user_id",
        cascade="all, delete-orphan"
    )
    
    # ============================================================
    # NEW: MATERIAL VIEW LOGS (MISSING - ADDED)
    # ============================================================
    material_view_logs = relationship(
        "MaterialViewLog",
        foreign_keys="MaterialViewLog.user_id",
        cascade="all, delete-orphan"
    )
    
    # ============================================================
    # NEW: ATTENDANCE AUDIT LOGS (MISSING - ADDED)
    # ============================================================
    attendance_audit_logs = relationship(
        "AttendanceAuditLog",
        foreign_keys="AttendanceAuditLog.changed_by",
        cascade="all, delete-orphan"
    )
    
    # ============================================================
    # NEW: ENROLLMENT HISTORY (MISSING - ADDED)
    # ============================================================
    enrollment_histories = relationship(
        "EnrollmentHistory",
        foreign_keys="EnrollmentHistory.action_by",
        cascade="all, delete-orphan"
    )
    
    # ============================================================
    # NEW: COUPON USAGE
    # ============================================================
    coupon_usages = relationship(
        "CouponUsage",
        back_populates="user",
        foreign_keys="CouponUsage.user_id",
        cascade="all, delete-orphan"
    )
    
    # ============================================================
    # NEW: SOFTWARE HOUSE RELATIONSHIPS
    # ============================================================
    # Project assignments
    project_assignments = relationship(
        "ProjectAssignment",
        back_populates="user",
        foreign_keys="ProjectAssignment.user_id",
        cascade="all, delete-orphan"
    )
    
    # Task assignments
    assigned_tasks = relationship(
        "ProjectTask",
        back_populates="assigned_to_user",
        foreign_keys="ProjectTask.assigned_to",
        cascade="all, delete-orphan"
    )
    
    # Tasks created
    created_tasks = relationship(
        "ProjectTask",
        back_populates="created_by_user",
        foreign_keys="ProjectTask.created_by",
        cascade="all, delete-orphan"
    )
    
    # Time entries
    time_entries = relationship(
        "TimeEntry",
        back_populates="user",
        foreign_keys="TimeEntry.user_id",
        cascade="all, delete-orphan"
    )
    
    # Task comments
    task_comments = relationship(
        "TaskComment",
        back_populates="user",
        foreign_keys="TaskComment.user_id",
        cascade="all, delete-orphan"
    )
    
    # Invoices created
    invoices_created = relationship(
        "Invoice",
        back_populates="created_by_user",
        foreign_keys="Invoice.created_by",
        cascade="all, delete-orphan"
    )
    
    # ============================================================
    # NEW: AI HUB RELATIONSHIPS
    # ============================================================
    ai_agents_created = relationship(
        "AIAgent",
        back_populates="created_by_user",
        foreign_keys="AIAgent.created_by",
        cascade="all, delete-orphan"
    )
    
    ai_agent_subscriptions = relationship(
        "AIAgentSubscription",
        back_populates="user",
        foreign_keys="AIAgentSubscription.user_id",
        cascade="all, delete-orphan"
    )
    
    ai_training_data_uploaded = relationship(
        "AITrainingData",
        back_populates="uploaded_by_user",
        foreign_keys="AITrainingData.uploaded_by",
        cascade="all, delete-orphan"
    )
    
    ai_api_keys = relationship(
        "AIApiKey",
        back_populates="user",
        foreign_keys="AIApiKey.user_id",
        cascade="all, delete-orphan"
    )
    
    ai_api_logs = relationship(
        "AIApiLog",
        back_populates="user",
        foreign_keys="AIApiLog.user_id",
        cascade="all, delete-orphan"
    )
    
    # ============================================================
    # REPRESENTATION
    # ============================================================
    
    def __repr__(self) -> str:
        return f"<User {self.email}>"
    
    def __str__(self) -> str:
        return self.full_name or self.email
    
    # ============================================================
    # HELPER METHODS (EXISTING - KEPT)
    # ============================================================
    
    @property
    def is_student(self) -> bool:
        """Check if user is a student."""
        return self.role == UserRole.STUDENT
    
    @property
    def is_teacher(self) -> bool:
        """Check if user is a teacher."""
        return self.role == UserRole.TEACHER
    
    @property
    def is_admin(self) -> bool:
        """Check if user is an admin."""
        return self.role == UserRole.ADMIN
    
    @property
    def is_client(self) -> bool:
        """Check if user is a client (Software House)."""
        return self.role == UserRole.CLIENT
    
    @property
    def is_developer(self) -> bool:
        """Check if user is a developer (Software House)."""
        return self.role == UserRole.DEVELOPER
    
    @property
    def is_deleted(self) -> bool:
        """Check if user is soft-deleted."""
        return self.deleted_at is not None
    
    # ============================================================
    # NEW: EXTENDED HELPER METHODS
    # ============================================================
    
    @property
    def is_locked(self) -> bool:
        """Check if user account is locked."""
        if self.locked_until is None:
            return False
        return self.locked_until > func.now()
    
    @property
    def has_student_id(self) -> bool:
        """Check if user has a student ID assigned."""
        return self.student_id is not None
    
    @property
    def display_name(self) -> str:
        """Get display name (full name or email)."""
        return self.full_name if self.full_name else self.email
    
    @property
    def role_display(self) -> str:
        """Get human-readable role name."""
        role_map = {
            UserRole.STUDENT: "Student",
            UserRole.TEACHER: "Teacher",
            UserRole.ADMIN: "Administrator",
            UserRole.CLIENT: "Client",
            UserRole.DEVELOPER: "Developer",
        }
        return role_map.get(self.role, str(self.role))
    
    # ============================================================
    # SOFT DELETE METHODS (EXISTING - KEPT)
    # ============================================================
    
    def soft_delete(self) -> None:
        """Soft delete the user."""
        self.deleted_at = func.now()
    
    def restore(self) -> None:
        """Restore a soft-deleted user."""
        self.deleted_at = None
    
    def activate(self) -> None:
        """Activate the user account."""
        self.is_active = True
    
    def deactivate(self) -> None:
        """Deactivate the user account."""
        self.is_active = False
    
    def verify(self) -> None:
        """Mark user as verified."""
        self.is_verified = True
    
    def unverify(self) -> None:
        """Mark user as unverified."""
        self.is_verified = False
    
    # ============================================================
    # NEW: SECURITY METHODS
    # ============================================================
    
    def increment_failed_login(self) -> None:
        """Increment failed login attempts and lock if needed."""
        self.failed_login_attempts += 1
        
        # Lock after 5 failed attempts
        if self.failed_login_attempts >= 5:
            self.locked_until = func.now() + func.interval('30 minutes')
    
    def reset_failed_login_attempts(self) -> None:
        """Reset failed login attempts on successful login."""
        self.failed_login_attempts = 0
        self.locked_until = None
    
    def unlock_account(self) -> None:
        """Manually unlock the account."""
        self.failed_login_attempts = 0
        self.locked_until = None
    
    def update_last_login(self) -> None:
        """Update last login timestamp."""
        self.last_login = func.now()
    
    # ============================================================
    # NEW: STUDENT ID GENERATION (will be handled by DB trigger)
    # ============================================================
    # The database trigger will auto-generate student_id when role = 'student'
    # Format: AETH-XXXXX (e.g., AETH-00042)
    # This is defined in the database, not in code
    
    # ============================================================
    # NEW: TO-DICT METHOD (for API responses)
    # ============================================================
    
    def to_dict(self, include_sensitive: bool = False) -> dict:
        """Convert user to dictionary for API responses."""
        data = {
            "id": self.id,
            "email": self.email,
            "username": self.username,
            "full_name": self.full_name,
            "phone": self.phone,
            "profile_picture": self.profile_picture,
            "bio": self.bio,
            "role": self.role.value if self.role else None,
            "student_id": self.student_id,
            "is_verified": self.is_verified,
            "is_active": self.is_active,
            "last_login": self.last_login.isoformat() if self.last_login else None,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "updated_at": self.updated_at.isoformat() if self.updated_at else None,
        }
        
        # Include sensitive data only when requested (admin only)
        if include_sensitive:
            data["failed_login_attempts"] = self.failed_login_attempts
            data["is_locked"] = self.is_locked
            data["locked_until"] = self.locked_until.isoformat() if self.locked_until else None
            data["deleted_at"] = self.deleted_at.isoformat() if self.deleted_at else None
        
        return data
    
    # ============================================================
    # NEW: JSON RESPONSE METHODS (for FastAPI)
    # ============================================================
    
    def to_public_json(self) -> dict:
        """Public-facing user data (safe for any response)."""
        return {
            "id": self.id,
            "full_name": self.full_name,
            "email": self.email,
            "username": self.username,
            "profile_picture": self.profile_picture,
            "bio": self.bio,
            "role": self.role.value if self.role else None,
            "student_id": self.student_id,
            "is_verified": self.is_verified,
        }
    
    def to_private_json(self) -> dict:
        """Private user data (for user's own profile)."""
        data = self.to_public_json()
        data.update({
            "phone": self.phone,
            "last_login": self.last_login.isoformat() if self.last_login else None,
            "is_active": self.is_active,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "updated_at": self.updated_at.isoformat() if self.updated_at else None,
        })
        return data
    
    def to_admin_json(self) -> dict:
        """Admin user data (full access)."""
        data = self.to_private_json()
        data.update({
            "failed_login_attempts": self.failed_login_attempts,
            "locked_until": self.locked_until.isoformat() if self.locked_until else None,
            "deleted_at": self.deleted_at.isoformat() if self.deleted_at else None,
        })
        return data